version: "3.8"

services:
  webapp:
    container_name: telegram-workflow-webapp
    build:
      context: .
      dockerfile: ./apps/webapp/Dockerfile
    ports:
      - 3000:3000

  api:
    container_name: telegram-workflow-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: telegram-workflow-database
    ports:
      - 5432:5432
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
